# build.ps1 — UEVR (luavrlib)
# Generated by Progress Dashboard · 2026-05-25

$ErrorActionPreference = "Stop"
$RepoRoot = "I:/code/lobotomy-x/UEVR"
$BuildDir = Join-Path $RepoRoot "build"
$Config   = "RelWithDebInfo"

Push-Location $RepoRoot
try {
  Write-Host "[1/4] Verifying branch · expecting luavrlib"
  git rev-parse --abbrev-ref HEAD

  Write-Host "[2/4] Configuring CMake · $Config"
  if (-not (Test-Path $BuildDir)) { New-Item -ItemType Directory $BuildDir | Out-Null }
  cmake -S . -B $BuildDir -A x64

  Write-Host "[3/4] Building · $Config"
  cmake --build $BuildDir --config $Config -- /m

  Write-Host "[4/4] Done · artifacts in $BuildDir\bin\$Config"
} finally {
  Pop-Location
}
